(********************************************************************
 * COPYRIGHT --  
 ********************************************************************
 * Program: FestoControl
 * File: FestoControlInit.st
 * Author: jorkes
 * Created: September 17, 2014
 ********************************************************************
 * Implementation of program FestoControl
 ********************************************************************)

PROGRAM _INIT

	i := 0;

END_PROGRAM

