(********************************************************************
 * COPYRIGHT -- Microsoft
 ********************************************************************
 * Program: IOpolling
 * File: IOpolling.st
 * Author: jorkes
 * Created: October 24, 2014
 ********************************************************************
 * Implementation of program IOpolling
 ********************************************************************)

PROGRAM _INIT
	
END_PROGRAM


PROGRAM _CYCLIC
	
	ElevatorCil(BU[0], BU[i].typIN.bElevatorUp, BU[i].typIN.bElevatorMid, BU[i].typIN.bElevatorDown);
	
END_PROGRAM
